swagger: '2.0'
info:
  version: '1.0.0'
  title: SARAKEL API
paths:
  /login/forget_username:
    post:
      summary: Retrieve forgotten username
      description: This endpoint sends an email to the user with their username if the provided email is associated with an account.
      operationId: forgetUsername
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          description: Email of the user
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                description: Email of the user
      responses:
        '200':
          description: correct credentials, user logged in
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation was successful
              message:
                type: string
                description: success message
        '400':
          description: Bad request, username and password required
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
              message:
                type: string
                description: missing parameter/s
          
        '404':
          description: user not found
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
              message:
                type: string
                description: message indicating email is not associated with an account

        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation failed
              message:
                type: string
                description: Error message
      tags:
        - Users
