swagger: '2.0'
info:
  version: '1.0.0'
  title: SARAKEL API
paths:
  /api/comment:
    post:
      summary: Create a new comment
      description: Creates a new comment on a post
      parameters:
        - in: body
          name: comment
          description: Comment details
          required: true
          schema:
            type: object
            properties:
              postId:
                type: string
                description: The ID of the post to comment on
              content:
                type: string
                description: The content of the comment
      responses:
        '200':
          description: Comment created successfully
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              data:
                type: object
                properties:
                  commentId:
                    type: string
                    description: Unique identifier for the comment
        '500':
          description: Failed to create comment
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Error message
      tags:
        - Comments
      operationId: createComment
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - AuthorizationCode: []
securityDefinitions:
  AuthorizationCode:
    type: oauth2
    # authorizationUrl: "https://www.example.com/oauth2/authorize"
    # tokenUrl: "https://www.example.com/oauth2/token"
    flow: authorizationCode
    scopes:
      create_comment: Allow creating new comments
