swagger: '2.0'
info:
  version: '1.0.0'
  title: SERAKEL API

paths:
  /api/remove:
    post:
      summary: remove a link or comment
      description: This endpoint is used to remove a link, comment, or modmail message. If the thing is a link, it will be removed from all subreddit listings. If the thing is a comment, it will be redacted and removed from all subreddit comment listings
      parameters:
        - name: id
          in: query
          description: Fullname of a thing
          required: true
          type: string
        - name: spam
          in: query
          description: Boolean value
          required: false
          type: boolean
        - name: Authorization
          in: header
          description: OAuth token
          required: true
          type: string
          format: "Bearer {token}"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation was successful
        401:
          description: The token is either expired or does not grant access to this operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation blocked
        404:
          description: The ID of the post or link passed does not exist
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
        500:
          description: Server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
      tags:
        - Moderation
      security:
        - AuthorizationCode: []
securityDefinitions:
  AuthorizationCode:
    type: oauth2
    authorizationUrl: "https://www.example.com/oauth2/authorize"
    tokenUrl: "https://www.example.com/oauth2/token"
    flow: accessCode