swagger: '2.0'
info:
  version: '1.0.0'
  title: SERAKEL API

paths:
  /api/show_comment:
    post:
      summary: Mark a comment that it should not be collapsed because of crowd control
      description: This endpoint is used to mark a comment so that it doesn't get collapsed because of crowd control. The comment could still be collapsed for other reasons.
      parameters:
        - name: id
          in: query
          description: Fullname of a thing
          required: true
          type: string
        - name: Authorization
          in: header
          description: OAuth token
          required: true
          type: string
          format: "Bearer {token}"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation was successful
        401:
          description: The token is either expired or does not grant access to this operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation blocked
        404:
          description: The ID of the post or link passed does not exist
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
        500:
          description: Server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
          
      tags:
        - Moderation

      security:
        - AuthorizationCode: []
securityDefinitions:
  AuthorizationCode:
    type: oauth2
    authorizationUrl: "https://www.example.com/oauth2/authorize"
    tokenUrl: "https://www.example.com/oauth2/token"
    flow: accessCode