swagger: '2.0'
info:
  version: '1.0.0'
  title: SERAKEL API
paths:
  /api/unhide:
    post:
      summary: Unhide a hidden item
      description: Unhides a previously hidden item
      parameters:
        - in: body
          name: unhideDetails
          description: Details for unhiding a hidden item
          required: true
          schema:
            type: object
            properties:
              type:
                type: string
                description: The typr(comment/post) to be hidden
              entityId:
                type: string
                description: The ID of the post/comment  wants to hide the link
      responses:
        '200':
          description: Item unhidden successfully
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Success message indicating that the item was unhidden successfully
        '500':
          description: Failed to unhide item
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Error message
      tags:
        - Hide
      operationId: unhideItem
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - AuthorizationCode: []
