swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Reddit Clone API'
paths:
  /api/v1/me:
    get:
      summary: Returns the identity of the user.
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              id:
                type: string
              username:
                type: string
      tags: 
        - Users
