swagger: '2.0'
info:
  version: '1.0.0'
  title: SARAKEL API

paths:
  /api/approve:
    post:
      summary: Approve a link or comment
      description: This endpoint is used by a moderator to approve a link or comment. If the thing was removed, it will be re-inserted into appropriate listings. Any reports on the approved thing will be discarded.
      parameters:
        - name: id
          in: query
          description: Fullname of a thing
          required: true
          type: string
        - name: Authorization
          in: header
          description: OAuth token
          required: true
          type: string
          format: "Bearer {token}"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation was successful
        401:
          description: The token is either expired or does not grant access to this operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation blocked
        404:
          description: The ID of the post or link passed does not exist
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
        500:
          description: Server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
          
      tags:
        - Moderation

      security:
        - AuthorizationCode: []
securityDefinitions:
  AuthorizationCode:
    type: oauth2
    authorizationUrl: "https://www.example.com/oauth2/authorize"
    tokenUrl: "https://www.example.com/oauth2/token"
    flow: accessCode