swagger: '2.0'
info:
  version: '1.0.0'
  title: SARAKEL API
paths:
  /login:
    post:
      summary: User login
      description: This endpoint authenticates a user based on their username and password.
      operationId: logIn
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: userCredentials
          required: true
          schema:
            type: object  
            properties:
              username:
                type: string
                description: Username
              password:
                type: 'string'
                description: Password
      responses:
        '200':
          description: correct credentials, user logged in
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation was successful
              message:
                type: string
                description: success message
        '400':
          description: Bad request, username and password required
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
              message:
                type: string
                description: missing parameter/s
          
        '401':
          description: invalid username or password
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
              message:
                type: string
                description: message indicating incorrect credentials

        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation failed
              message:
                type: string
                description: Error message
      tags:
        - Users

