swagger: '2.0'
info:
  version: '1.0.0'
  title: SERAKEL API

paths:
  /subreddits/mine/moderator:
    get:
      summary: Return a listing of posts relevant to moderators
      description: This endpoint returns a listing of posts that are relevant to moderators. The categories include reports, spam, modqueue, and unmoderated, only one of before and after should be provided .
      parameters:
        - name: after
          in: query
          description: Fullname of a thing
          required: false
          type: string
        - name: before
          in: query
          description: Fullname of a thing
          required: false
          type: string
        - name: count
          in: query
          description: A positive integer
          required: false
          type: integer
          format: int32
        - name: limit
          in: query
          description: The maximum number of items desired
          required: false
          type: integer
          format: int32
        - name: show
          in: query
          description: Optional, the string all
          required: false
          type: string
        - name: sr_detail
          in: query
          description: Optional, expand subreddits
          required: false
          type: boolean
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Operation was successful
        500:
          description: Server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Operation failed
      tags: 
        - Moderation


