swagger: '2.0'
info:
  version: '1.0.0'
  title: SARAKEL API
paths:
  /api/subreddit/hot:
    get:
      summary: Get hot subreddit
      description: Gets the hot subreddit by Id
      parameters:
        - in: query
          name: postId
          description: Subreddit Id
          required: true
          type: number
        - in: body
          name: subreddit details
          description: Additional details about the subreddit
          required: true
          schema:
            type: object
            properties:
              gethotId:
                type: number
                description: Id of subreddit
      responses:
        '200':
          description: hot subreddit sent successfully
          schema:
            type: object
            properties:
              success: 
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Success message indicating that hot subreddit sent successfully
        '500':
          description: Failed to get hot subreddit
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was unsuccessful
              message:
                type: string
                description: Error message
      tags:
        - Subreddit
        
      operationId: hotSubreddit
      produces:
        - application/json
                
                
                
                
                
                