swagger: '2.0'
info:
  version: '1.0.0'
  title: SERAKEL API
paths:
  /api/unsave:
    post:
      summary: unsave a post or comment
      description: unsaves a post or comment to the user's unsaved items
      parameters:
        - in: body
          name: unsaveDetails
          description: Details for saving a post or comment
          required: true
          schema:
            type: object
            properties:
              type:
                type: string
                description: The typr(comment/post) to be hidden
              entityId:
                type: string
                description: The ID of the post/comment  wants to hide the link
      responses:
        '200':
          description: Post or comment unsaved successfully
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Success message indicating that the post or comment was unsaved successfully
        '500':
          description: Failed to unsave post or comment
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Error message
      tags:
        - Save
      operationId: savePostOrComment
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - UserAuth: []
