swagger: '2.0'
info:
  version: '1.0.0'
  title: SERAKEL API

paths:
  /r/{subreddit}/api/accept_moderator_invite:
    post:
      summary: Accept an invite to moderate the specified subreddit
      description: This endpoint is used to accept an invite to moderate the specified subreddit. The authenticated user must have been invited to moderate the subreddit by one of its current moderators.
      parameters:
        - name: subreddit
          in: path
          description: name of the subreddit
          required: true
          type: string
          
        - name: api_type
          in: query
          description: The string json
          required: true
          type: string
        - name: Authorization
          in: header
          description: OAuth token
          required: true
          type: string
          format: "Bearer {token}"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Operation was successful
        401:
          description: The token is either expired or does not grant access to this operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Operation blocked
        500:
          description: Server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Operation failed

      tags:
        - Moderation

      security:
        - AuthorizationCode: []
securityDefinitions:
  AuthorizationCode:
    type: oauth2
    authorizationUrl: "https://www.example.com/oauth2/authorize"
    tokenUrl: "https://www.example.com/oauth2/token"
    flow: accessCode
