swagger: '2.0'
info:
  version: '1.0.0'
  title: SERAKEL API

paths:
  /api/site_admin:
    post:
      summary: Create or configure a subreddit
      description: This endpoint is used to create or configure a subreddit. If 'sr' is specified, the request will attempt to modify the specified subreddit. If not, a subreddit with name 'name' will be created.
      parameters:
        - name: body
          in: body
          description: Parameters
          required: true
          schema:
            type: object
            properties:
              api_type:
                type: string
                description: The string json
                
              accept_followers:
                type: boolean
                description: Boolean value

              sr:
                type: string
                description: The name of the subreddit
                
              allow_images:
                type: boolean
                description: allow users to post images
                
              description: 
                type: string
                description: description of the subreddit    
        - name: Authorization
          in: header
          description: OAuth token
          required: true
          type: string
          format: "Bearer {token}"

      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Operation was successful
        401:
          description: The token is either expired or does not grant access to this operation
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Operation blocked
        500:
          description: Server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Operation failed
      tags: 
        - Moderation
      security:
        - AuthorizationCode: []
securityDefinitions:
  AuthorizationCode:
    type: oauth2
    authorizationUrl: "https://www.example.com/oauth2/authorize"
    tokenUrl: "https://www.example.com/oauth2/token"
    flow: accessCode

