swagger: '2.0'
info:
  version: '1.0.0'
  title: Reddit Clone API
paths:
  /api/v1/me/friends/{username}:
    delete:
      summary: Remove a friend
      description: Removes a friend from the authenticated user's friend list
      parameters:
        - in: path
          name: username
          description: The username of the friend to be removed
          required: true
          type: string
      responses:
        '200':
          description: Friend removed successfully
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Success message indicating that the friend was removed successfully
        '400':
          description: Bad request, e.g., the friend does not exist
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Error message
        '500':
          description: Server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation was successful
              message:
                type: string
                description: Error message
      tags:
        - Users
      operationId: removeFriend
      produces:
        - application/json
