swagger: '2.0'
info:
  version: '1.0.0'
  title: SARAKEL API
paths:
  /login/reset_password:
    post:
      summary: Reset password
      description: This endpoint resets the user's password. It is accessed when the user enters and verifies their new password.
      operationId: resetPassword
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: new password
          description: New password details
          required: true
          schema:
            type: object
            properties:
              password:
                type: string
                description: New password of the user
              confirm_password:
                type: string
                description: Confirmation of the new password
      responses:
        '200':
          description: correct credentials, user logged in
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation was successful
              message:
                type: string
                description: success message
        '400':
          description: Bad request, username and password required
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
              message:
                type: string
                description: missing parameter/s
          
        '401':
          description: invalid authentication token
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: opearation failed
              message:
                type: string
                description: message with error details

        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: Indicates whether the operation failed
              message:
                type: string
                description: Error message
      tags:
        - Users
